### ISSUE TITLE
Discussion: Design and colors

### ISSUE THREAD

**Issue by casassg** [hackupc/baggage#5]
@hackupc/design let's move the baggage UI design conversation here!

**Comment by oriol20** [comment]
Centered logo
![baggage v2](https://user-images.githubusercontent.com/10714286/29091751-3a00e398-7c84-11e7-91dd-e7bd53094260.png)

Side logo v1
![baggage v3](https://user-images.githubusercontent.com/10714286/29091724-27e079bc-7c84-11e7-8b15-0e10e71b278b.png)

Side logo v2
![baggage v4](https://user-images.githubusercontent.com/10714286/29092279-24205df4-7c86-11e7-9205-0f2711d09c97.png)

I personally prefer the sided v2, but also the centered because the sided v1 seems really squared.

**Comment by casassg** [comment]
You can find the font Gotham Regular that @elena20ruiz mentioned on hackupc/frontend

**Comment by elena20ruiz** [comment]
All options seems nice for me @oriol :) I think I will let you choice you're favorite. I can't decide.
